### ISSUE TITLE
这是什么问题呢

### ISSUE THREAD

**Issue by jtning** [fankcoder/findtrip#2]
Traceback (most recent call last):
  File "e:\program files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Program Files (x86)\Python\Scripts\scrapy.exe\__main__.py", line 9, in <module>
  File "e:\program files (x86)\python\lib\site-packages\scrapy\cmdline.py", line 129, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "e:\program files (x86)\python\lib\site-packages\scrapy\cmdline.py", line 51, in _get_commands_dict
    cmds.update(_get_commands_from_module(cmds_module, inproject))
  File "e:\program files (x86)\python\lib\site-packages\scrapy\cmdline.py", line 30, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "e:\program files (x86)\python\lib\site-packages\scrapy\cmdline.py", line 20, in _iter_command_classes
    for module in walk_modules(module_name):
  File "e:\program files (x86)\python\lib\site-packages\scrapy\utils\misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "e:\program files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Cache\1\findtrip\commands\crawlall.py", line 34
    spider_loader = self.crawler_process.spider_loader
                                                     ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by fankcoder** [comment]
检查下你的编辑器缩进，或者使用4个空格替代tab
